package com.pan.myfriendsapp.api.user.repository;

import com.pan.myfriendsapp.api.user.model.User;
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserRepository extends JpaRepository<User, Long> {

    // Spring auto-generates this query!

    /**
     * These methods are also auto-generated by JPA
     * save()
     * findById()
     * findAll()
     * deleteById()
     */

    User findByName(String name);
}
